forem/selfhost

- README.md
Updates prerequisites to explicitly mention both `ansible-core` (2.11, which matches `ansible_version_required`) and Ansible versions.
> Add note about ansible-core vs ansible versions

- README.md
~clarify that "pass the api token" digital ocean is done via a command line switch --access-token~
Update documentation to clarify auth init behavior if a --context arg was passed requires auth switch prior to using ansible next.
> Update DO token auth instructions

- README.md
- inventory/providers/gcp/gcp.yml
- playbooks/providers/gcp.yml
Rename `forem_gcp_project` to `forem_gcp_project_id`, as it's specifically the GCP Project ID string that is used by the Ansible modules, not the Project Name.
> Rename var forem_gcp_project to forem_gcp_project_id

- README.md
A creator had a question about this step, which we discussed internally: https://forem-team.slack.com/archives/C023Z19ELNB/p1626275810177800
This adds a direct link to the example inventory where we provide the explicit commands that can be used to generate vaulted Ansible variables.
> Add link and explicit wording about generating secrets

- README.md
A small change to the installation instructions for getting pip3 on a Mac. `brew install python3` is required to get not only Python 3.x on a macOS, but also `pip3`.
> Update install instructions for python 3.x/pip3 on macOS

- inventory/example/setup.yml
- inventory/providers/qemu/static.yml
We no longer use Elastic Search, so I removed configuration settings related to Elastic Search.
> Removed Elastic search from configuration files.

- roles/preflight/tasks/main.yml
Closes #7 
The `checkip.amazonaws.com` domain should only return an IPv4 public WAN address:
```
~ $ curl -4 "https://checkip.amazonaws.com/"
75.XXX.XXX.XXX
~ $ curl -6 "https://checkip.amazonaws.com/"
curl: (6) Could not resolve host: checkip.amazonaws.com
```
> Use AWS to retrieve IPv4 IP

- README.md
- playbooks/providers/aws.yml
- playbooks/providers/digitalocean.yml
- playbooks/providers/gcp.yml
- Butane template was redirecting to `selfhost-devel` repository, which was empty -> Remapped to `selfhost` repository
- Admins docs were being referred to Netlify domain(https://forem-admin.netlify.app/) -> Remapped to Forem Domain(https://admin.forem.com/)
- Reduced the length of the bullet point and highlighted the Note using a quotation tag.
At the end of every successful Forem installation, we have a deployment success message, in which the Admin Docs are also referred to the Netlify domain, rather than the Forem domain.
> akhil-naidu/README_typos

- playbooks/templates/forem.yml.j2
The `forem-pod.service` should want the `forem-imgproxy.service` before it can start. Otherwise without it, we will have busted images on a Forem.
> Add forem-imgproxy.service to Wants on forem-pod.service

- requirements.yml
We forgot to add in `google.cloud` to the `requirements.yml` file. Woops!
> Add google.cloud to requirements.yml

- playbooks/templates/forem.yml.j2
This backports a fix for an issue seen in Forem Cloud, where `forem-container.service` would run too quickly on initial boot, and be unable to pull the app container image down (but the service wouldn't fail, due to the `exit 0` in the affected `if` block inside `foremimg`).
> Add retry logic to forem-container service

- README.md
Adding a section to explain that an RSA-based key is needed for AWS in step 7 of the Quick Start guide.
> Quickstart SSH update

- inventory/example/setup.yml
- playbooks/templates/forem.yml.j2
I suspect youtube embedded video playback is not working if referrer policy is set to "same-origin". 
Add a configuration variable to support relaxing this during setup.
Add a hint in setup.yml that you might change this, and a note in the generated toml file that this came from a variable upstream.
> Add referrer policy option

- inventory/example/setup.yml
- playbooks/templates/forem.yml.j2
Reverts forem/selfhost#38
One thing to note - after this change a required variable _must_ be added to the inventory/forem/setup.yml which is only present in the inventory/example/setup.yml  
This will impact users who (1) already cloned the repo and copied/customized the setup.yml file (2) subsequently pull the current git head
> Add referrer policy option again

- playbooks/templates/forem.yml.j2
Fixes an error seen when starting traefik due to an unquoted string
```
*file.Provider: Near line 22 (last key parsed 'http.middlewares.security.headers.ReferrerPolicy'): expected value but found \"same\" instead"
```
On main - building in qemu - the resulting /opt/forem/configs/traefik/dynamic.toml includes an unquoted string for referrer policy:
ReferrerPolicy = same-origin
On this branch the generated toml file quotes that value
ReferrerPolicy = "same-origin"
> Surround value with quotes

- README.md
This PR adds an example for using the `-i identify_file` option with `ssh`.  In step 5 of the installation instructions, we tell people to generate a key in `${HOME}/.ssh/forem` but the examples didn't show how to use such a key. This tripped up Rajat when he attempted a selfhost install and we resolved this on a call, so I figured it's probably better to add it to the README.
> Add second SSH example to README

- README.md
Include -p (preserve permissions) to the tar command when backing up Forem data.
> Updates tar flags on backup command

- README.md
- inventory/example/setup.yml
Readme link was a few lines too early (probably an insertion further
up), change line 64 to line 67 so the link points to the right
location.
I ran into a confusing situation running what looked like normal shell
commands to pass random data to ansible-vault, where a password was
prompted for, and decrypting the vault secrets in the yaml file
failed. The hidden context was that the commands must run in the selfhost 
directory for the vault encryption to use the same password as the playbook.
Add a safeguard note that you should be in the selfhost
directory (where the ansible.cfg file is present) before running the
shell commands, and a hint that being prompted for a password is an
indication that something went wrong.
> Add comment about ansible-vault, and update the readme link

- inventory/example/setup.yml
- inventory/providers/qemu/static.yml
- playbooks/templates/forem.yml.j2
Refs an internal infra issue where we wanted to clean up env vars that are no longer ref'd anywhere in forem/forem (or within any Forem Cloud infra).
> terraform/env: Remove unused pusher_* references.

- roles/fcos/defaults/main.yml
Fedora have changed their key URL, updating it to the new one as detailed in https://fedoraproject.org/security/
> Update new gpg key location for fcos image
